name: Lint workflow files
on:
  push:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Test
        run: devenv test
